# Generated by Django 3.2.18 on 2023-03-08 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('src', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teacher',
            name='webinar',
        ),
        migrations.AddField(
            model_name='teacher',
            name='webinar',
            field=models.ManyToManyField(to='src.Webinar'),
        ),
    ]
