# Generated by Django 3.2.18 on 2023-03-08 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('src', '0002_auto_20230308_1316'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacher',
            name='webinar',
            field=models.ManyToManyField(related_name='teacher_webinar', to='src.Webinar', verbose_name='Вебинары преподавателя'),
        ),
    ]
