# Generated by Django 3.2.18 on 2023-03-08 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('src', '0005_auto_20230308_1338'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacher',
            name='course',
            field=models.ManyToManyField(blank=True, to='src.Course', verbose_name='Курсы преподавателя'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='webinar',
            field=models.ManyToManyField(blank=True, to='src.Webinar', verbose_name='Вебинары преподавателя'),
        ),
    ]
